### ISSUE TITLE
Tracker: Neovim

### ISSUE THREAD

**Issue by TomJo2000** [TomJo2000/.dotfiles#11]
- [ ] Hydra
  - [x] Make the Git Hydra work nicely
    - [ ] Change keybinds on the hunk preview jumping
    - [ ] stop it from turning off the signcolumn when exiting
  - [ ] Make the Replacer Hydra work nicely
  - [ ] Get the resizer Hydra working
- [ ] Add a Git commit helper (working name, `forgit-me-not`), based on the `git staged` alias
https://github.com/TomJo2000/.dotfiles/blob/61eec86b0db4e8bd3f7fb232b42b2a36c94303d1/.config/git/config#L25-L29
- [x] [none-ls](https://github.com/nvimtools/none-ls.nvim) - see if I have a usecase for this
- [x] lualine
  - [x] change the save icon
  - [ ] various unplanned tweaks and changes to the statusline

**Comment by TomJo2000** [comment]
Good enough for now.
