### ISSUE TITLE
Proper deployment utility (deferred to whenever)

### ISSUE THREAD

**Issue by TomJo2000** [TomJo2000/.dotfiles#8]
- [ ] Deploy Script
  - [ ] (started but unfinished) Parse arguments
  - [x] loop through deploy specs in `.config/meta/deploy.d/*`
- [x] Deploy specs
  - [x] provides a `requires` and `locations` array for dependencies and deployment locations
  - [x] verify hash of deploy specs.
  - [x] let deploy specs overwrite the default deploy functions if required
- [ ] Make `deploy` test the "coverage" of the folders in the repo against deploy specs.
- [ ] Deal with permissions, probably through a post-clone `chmod` hook.

**Comment by TomJo2000** [comment]
Moved to: "Whenever".
Trying to do all of this all at once was too much and stalled the whole thing for 3 months.

I'm sick of deploying manually so I just made a minimum viable deployment script for the time being.

**Comment by TomJo2000** [comment]
Superseded by switching to `just`
