### ISSUE TITLE
Tracker: Readme stats.

### ISSUE THREAD

**Issue by TomJo2000** [TomJo2000/.dotfiles#9]
#### Tracker for progress on [`.config/meta/readme_stats.sh`](https://github.com/TomJo2000/.dotfiles/blob/main/.config/meta/readme_stats.sh)
- [x] c4f50b9: inital commit
- [x] b1353c1: Use scc
- [x] 33f3231: Configure scc
- [x] 55279fd: General improvements
- [x] fbc24eb: Prematurely declare victory
- [x] 6557c37: More fixes
- [x] `   n/a   `: Get the formatting figured out
  - I decided I no longer care that much.
